#!/usr/bin/env python3
"""Generate a small Python access-library/emulator proof from a chip profile.

This is intentionally narrow: it validates that the current profile can drive
one useful generated surface for SHT30 P0. It is not yet the final multi-chip
generator or a public runtime package.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def _hex_bytes(value: str) -> bytes:
    raw = value.removeprefix("0x")
    return bytes.fromhex(raw)


def _command_cases(profile: dict, operation_key: str, stretch: bool) -> dict[str, bytes]:
    commands = {item["key"]: item["code"] for item in profile["commands"]}
    operation = next(item for item in profile["operations"] if item["key"] == operation_key)
    return {
        item["repeatability"]: _hex_bytes(commands[item["command"]])
        for item in operation["command_cases"]
    }


def generate_sht30(profile: dict) -> str:
    if profile.get("chip") != "sht30" or profile.get("transport", {}).get("kind") != "i2c-command":
        raise ValueError("this proof generator currently supports only SHT30 command profiles")
    polling = _command_cases(profile, "single-shot-polling", stretch=False)
    stretching = _command_cases(profile, "single-shot-clock-stretch", stretch=True)
    crc = profile["transport"]["response_crc"]
    commands = {
        (repeatability, False): value.hex().upper() for repeatability, value in polling.items()
    } | {
        (repeatability, True): value.hex().upper() for repeatability, value in stretching.items()
    }
    command_lines = "\n".join(
        f"    ({repeatability!r}, {stretch!r}): bytes.fromhex({code!r}),"
        for (repeatability, stretch), code in sorted(commands.items())
    )
    return f'''# Generated by tools/generate.py from profiles/sht30.yaml. Do not edit.
from __future__ import annotations

from dataclasses import dataclass

COMMANDS = {{
{command_lines}
}}
CRC_POLYNOMIAL = {int(crc["polynomial"], 16)}
CRC_INIT = {int(crc["init"], 16)}


class NotReadyError(RuntimeError):
    pass


def crc8(data: bytes) -> int:
    value = CRC_INIT
    for byte in data:
        value ^= byte
        for _ in range(8):
            value = ((value << 1) ^ CRC_POLYNOMIAL) & 0xFF if value & 0x80 else (value << 1) & 0xFF
    return value


@dataclass(frozen=True)
class Measurement:
    temperature_raw: int
    humidity_raw: int


@dataclass(frozen=True)
class EmulatedRead:
    data: bytes
    scl_low_us: float


class SHT30Access:
    """Generated P0 access API. transport exposes write(bytes) and read(int)."""
    def __init__(self, transport):
        self.transport = transport

    def single_shot(self, repeatability: str, *, clock_stretch: bool = False) -> Measurement:
        command = COMMANDS[(repeatability, clock_stretch)]
        self.transport.write(command)
        frame = self.transport.read(6)
        if len(frame) != 6 or crc8(frame[:2]) != frame[2] or crc8(frame[3:5]) != frame[5]:
            raise ValueError("invalid SHT30 single-shot frame")
        return Measurement(int.from_bytes(frame[:2], "big"), int.from_bytes(frame[3:5], "big"))


class SHT30Emulator:
    """Generated command-state emulator with injected conversion timing.

    ``conversion_us_by_repeatability`` is supplied by the caller from an
    observation distribution; the profile records that it is not a universal
    fixed constant.
    """
    def __init__(self, *, temperature_raw: int, humidity_raw: int, conversion_us_by_repeatability: dict[str, float]):
        self.temperature_raw = temperature_raw
        self.humidity_raw = humidity_raw
        self.conversion_us_by_repeatability = conversion_us_by_repeatability
        self._pending: tuple[str, bool, float] | None = None

    def write(self, command: bytes, now_us: float) -> None:
        for (repeatability, stretch), known in COMMANDS.items():
            if command == known:
                self._pending = (repeatability, stretch, now_us + self.conversion_us_by_repeatability[repeatability])
                return
        raise ValueError("unsupported SHT30 P0 command")

    def read(self, now_us: float) -> EmulatedRead:
        if self._pending is None:
            raise NotReadyError("no pending single-shot measurement")
        repeatability, stretch, ready_at = self._pending
        remaining = max(0.0, ready_at - now_us)
        if remaining and not stretch:
            raise NotReadyError("single-shot result is not ready")
        frame = self.temperature_raw.to_bytes(2, "big")
        frame += bytes([crc8(frame)])
        humidity = self.humidity_raw.to_bytes(2, "big")
        frame += humidity + bytes([crc8(humidity)])
        self._pending = None
        return EmulatedRead(frame, remaining if stretch else 0.0)
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chip", required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    profile_path = REPO_ROOT / "profiles" / f"{args.chip}.yaml"
    profile = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
    if args.chip != "sht30":
        raise SystemExit("only --chip sht30 is supported by this proof generator")
    generated = generate_sht30(profile)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generated, encoding="utf-8")
    print(f"generated: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
